function DistributionPlots
clc;
clear;

t = 0:0.1:15;

%2->1 mean: 2min
% createfigure(t, expcdf(t,2), 'probability');
% createfigure( t, exppdf(t,2),'probability density');

%2->3 mean 8.45min sd=0.78
% createfigure(t, logncdf(t,2.12992, 0.092112),'probability');
% createfigure(t, lognpdf(t,2.12992, 0.092112),'probability density');

%3->4 [Vigorous to Interactive] Normal - Mean 5.55min sd=3.22 min
% createfigure(t, normcdf(t,5.55, 3.22),'probability');
% createfigure(t, normpdf(t,5.55, 3.22),'probability density');


%4->3 [Interactive to Vigorous] Exponential - Mean 1.5 min
% createfigure(t, expcdf(t,1.5), 'probability');
% createfigure( t, exppdf(t,1.5),'probability density');

%4->5[Interactive to Remote]		Exponential	- Mean	0.5	min
% createfigure(t, expcdf(t,0.5), 'probability');
% createfigure( t, exppdf(t,0.5),'probability density');

%5->4	[Remote to Interactive]	Exponential	- Mean	0.6	min
% createfigure(t, expcdf(t,0.6), 'probability');
% createfigure( t, exppdf(t,0.6),'probability density');

%5->6 [Remote to Full-room] Log-normal - Mean 5.18min	SD	4.18 min
%1.39406
%0.708155
% createfigure(t, logncdf(t,1.39406, 0.708155),'probability');
% createfigure(t, lognpdf(t,1.39406, 0.708155),'probability density');


%6->1	[Full-room to Non-fire]	Exponential	 Mean	5.1 min
createfigure(t, expcdf(t,5.1), 'probability');
createfigure( t, exppdf(t,5.1),'probability density');



function createfigure(x1, y1, Title)
%CREATEFIGURE(X1,Y1)
%  X1:  vector of x data
%  Y1:  vector of y data
 
%  Auto-generated by MATLAB on 26-Jan-2011 17:30:35
 
%% Create figure
figure1 = figure;
 
%% Create axes
axes1 = axes('FontSize',11,'Parent',figure1);
xlabel(axes1,'t');
ylabel(axes1,Title);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'all');
 
%% Create plot
plot1 = plot(...
  x1,y1,...
  'Color',[0 0 1],...
  'LineWidth',2.5);
 